parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'


    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']





    cv.admin.intro:
        class: AppBundle\Admin\IntroAdmin
        arguments: [~, AppBundle\Entity\Intro, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Intro
              group: "CV"
        public: true

    cv.admin.competence:
        class: AppBundle\Admin\CompetenceAdmin
        arguments: [~, AppBundle\Entity\Competence, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Competence
              group: "CV"
        public: true

    cv.admin.experience:
        class: AppBundle\Admin\ExperienceAdmin
        arguments: [~, AppBundle\Entity\Experience, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Experience
              group: "CV"
        public: true

    cv.admin.formation:
        class: AppBundle\Admin\FormationAdmin
        arguments: [~, AppBundle\Entity\Formation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Formation
              group: "CV"
        public: true

    cv.admin.realisation:
        class: AppBundle\Admin\RealisationAdmin
        arguments: [~, AppBundle\Entity\Realisation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Realisation
              group: "CV"
        public: true

    blog.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: User
              group: "Blog"
        public: true

    blog.admin.post:
        class: AppBundle\Admin\ArticleAdmin
        arguments: [~, AppBundle\Entity\Article, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Article
              group: "Blog"
        public: true

    blog.admin.comment:
        class: AppBundle\Admin\CommentAdmin
        arguments: [~, AppBundle\Entity\Comment, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Comment
              group: "Blog"
        public: true