<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\User;
use Doctrine\Bundle\FixturesBundle\Fixture;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadAppBundleEntityUser extends Fixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(User::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new User();
        $this->addReference('_reference_AppBundleEntityUser1', $item1);
        $item1->setUsername("benjamin");
        $item1->setUsernameCanonical("benjamin");
        $item1->setEmail("ben@test.com");
        $item1->setEmailCanonical("ben@test.com");
        $item1->setEnabled(true);
        $item1->setPassword("\$2y\$13\$kZ2.D93hZMVBGeyGBcgSEu7psh1SrjXneXfWUBrBeubhObbOMoORm");
        $item1->setLastLogin(new \DateTime("2018-01-14 14:03:16"));
        $item1->setRoles(unserialize('a:1:{i:0;s:16:"ROLE_SUPER_ADMIN";}'));

        $manager->persist($item1);

        $item2 = new User();
        $this->addReference('_reference_AppBundleEntityUser2', $item2);
        $item2->setUsername("manon");
        $item2->setUsernameCanonical("manon");
        $item2->setEmail("manon@test.com");
        $item2->setEmailCanonical("manon@test.com");
        $item2->setEnabled(true);
        $item2->setPassword("\$2y\$13\$O33yrBzvG9QWAljAlRsUSu0k91wrB9L6H4ggxdqcQH1x7Z.MQE6eG");
        $item2->setLastLogin(new \DateTime("2018-01-14 16:23:55"));

        $manager->persist($item2);

        $item3 = new User();
        $this->addReference('_reference_AppBundleEntityUser3', $item3);
        $item3->setUsername("bertrand");
        $item3->setUsernameCanonical("bertrand");
        $item3->setEmail("bertrand@test.com");
        $item3->setEmailCanonical("bertrand@test.com");
        $item3->setEnabled(true);
        $item3->setPassword("\$2y\$13\$Z2SYmTLd7T.t9tfHOnWefuRwHIM7IVvx2ImeIg.BHYJCHykmHNBmS");
        $item3->setLastLogin(new \DateTime("2018-01-15 07:33:12"));

        $manager->persist($item3);

        $item7 = new User();
        $this->addReference('_reference_AppBundleEntityUser7', $item7);
        $item7->setUsername("guigui");
        $item7->setUsernameCanonical("guigui");
        $item7->setEmail("guigui@test.com");
        $item7->setEmailCanonical("guigui@test.com");
        $item7->setEnabled(true);
        $item7->setPassword("\$2y\$13\$vrV7r8Q8o0jR0RvKhV2xJOitad6M1STuzjFUvpYXgcIyno.dY7h6O");
        $item7->setLastLogin(new \DateTime("2018-01-13 14:06:21"));

        $manager->persist($item7);

    
        $manager->flush();
    }

}
