<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\Formation;
use Doctrine\Bundle\FixturesBundle\Fixture;


/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadAppBundleEntityFormation extends Fixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Formation::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new Formation();
        $this->addReference('_reference_AppBundleEntityFormation1', $item1);
        $item1->setTitle("Etudiant 2ème année Ingesup @Ynov ");
        $item1->setYearStart("2016");
        $item1->setYearEnd("Aujourd'hui -");
        $item1->setContent("Expert en Architecture Réseau et Systèmes d'Information");

        $manager->persist($item1);

        $item2 = new Formation();
        $this->addReference('_reference_AppBundleEntityFormation2', $item2);
        $item2->setTitle("BPJEPS Loisirs Tous Publics");
        $item2->setYearStart("");
        $item2->setYearEnd("2011");
        $item2->setContent("avec les Francas d'Aquitaine ");

        $manager->persist($item2);

        $item3 = new Formation();
        $this->addReference('_reference_AppBundleEntityFormation3', $item3);
        $item3->setTitle("Baccalauréat L");
        $item3->setYearStart("");
        $item3->setYearEnd("2006 ");
        $item3->setContent("mention Bien");

        $manager->persist($item3);

    
        $manager->flush();
    }

}
