<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\Experience;
use Doctrine\Bundle\FixturesBundle\Fixture;


/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadAppBundleEntityExperience extends Fixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Experience::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new Experience();
        $this->addReference('_reference_AppBundleEntityExperience1', $item1);
        $item1->setTitle("Animateur socio-culturel ");
        $item1->setYear("2016 - 2015");
        $item1->setLocation("Centre d'animation Argonne - Bordeaux");
        $item1->setContent("création, suivi et gestion de la newsletter mensuelle
ateliers d'initiation à l'infographie
ateliers d'initiation au montage vidéo
ateliers seniors d'initiation à l'informatique
 ");

        $manager->persist($item1);

        $item2 = new Experience();
        $this->addReference('_reference_AppBundleEntityExperience2', $item2);
        $item2->setTitle("Stagiaire en Irlande");
        $item2->setYear("2014 - 2013");
        $item2->setLocation("Dublin - Irlande");
        $item2->setContent("travail avec un public difficile
ateliers d'initiation à l'infographie
ateliers d'initiation au montage vidéo
ateliers court-métrage");

        $manager->persist($item2);

        $item3 = new Experience();
        $this->addReference('_reference_AppBundleEntityExperience3', $item3);
        $item3->setTitle("Animateur Accueil de Loisirs");
        $item3->setYear("2012 - 2011");
        $item3->setLocation("Quinsac - Gironde");
        $item3->setContent("travail avec publics adolescents, enfants et familles
création et gestion de projets
ateliers d'accompagnement à la parentalité
ateliers de découvertes scientifiques
");

        $manager->persist($item3);

    
        $manager->flush();
    }

}
