<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\Article;
use Doctrine\Bundle\FixturesBundle\Fixture;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadAppBundleEntityArticle extends Fixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 2;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Article::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new Article();
        $this->addReference('_reference_AppBundleEntityArticle1', $item1);
        $item1->setUser($this->getReference('_reference_AppBundleEntityUser1'));
        $item1->setContent("Fin Septembre 2016. Je relis le mail que j’ai reçu sur mon téléphone portable m’annonçant ma rentrée pédagogique pour confirmer que je me trouve bien au bon endroit, à la bonne heure. C’est bon. Malgré cela, j’éprouve quand même une sensation un peu étrange : en effet cela me fait un peu bizarre d’être de retour sur les bancs de l’école. Il faut dire qu’il y a déjà quelques temps que je les ai quittés.

	Agé de 28 ans, je n’ai pas tout de suite été attiré par des études en informatique. A l’obtention de mon bac L en 2006 (fichtre, déjà si loin ?!) je m’étais d’abord destiné à des études de langues Anglais-Russe en vue d’un diplôme d’interprétariat. Mais le cadre (trop ?) libre de l’université aura eu raison de moi et je décidais alors d’abandonner mes études pour un moment. S’en sont suivis une année de service civil volontaire, un voyage à l’étranger, un diplôme d’animateur socio-culturel assorti d’une longue expérience de travail dans ce milieu pour que s’impose un constat malheureux à mes yeux : l’animation socio-culturelle et le travail social en général ne connaîtront pas d’autres choses que des réformes à la baisse et des restrictions budgétaires, couplées avec des conditions de travail de plus en plus difficiles et une absence de la moindre reconnaissance.
Je m’interroge alors sur mon avenir en pensant fortement : « j’aurais quand même bien aimé faire des études dans l’informatique… » Ce à quoi je me réponds moi-même qu’en fin de compte il n’est pas trop tard et que c’est maintenant ou jamais que je devrais me prendre en main.

	Des salons étudiants et quelques entretiens pédagogiques plus tard et me voilà ainsi le jour de la rentrée face à Yannick Nay, le directeur de l’école accompagné de l’équipe pédagogique qui nous présente l’école et la formation. Le ton est donné : on parle d’argent et de promesses d’avenir dès le début, du jamais vu dans le secteur social jusque-là pour moi !

	Les jours s’enchainent et je prends peu à peu mes marques : mon ordinateur portable est devenu mon outil de travail principal et les professeurs comme leurs cours visent à nous former en tant que futurs professionnels. L’école et son équipe pédagogique planifie d’ores et déjà des rendez-vous de suivi individuels et je me sens bien cadré : tout à fait ce dont j’avais besoin et dont je souffrais l’absence à la fac. 
Les cours défilent et j’apprends peu à peu des choses très variées qu’au fond j’avais toujours voulu connaitre : le fonctionnement mécanique d’un ordinateur, les bases d’un réseau, le raisonnement à avoir pour écrire des algorithmes, appréhender une base de données et savoir adresser des requêtes pour obtenir les résultats voulus, etc…

	Le niveau est plutôt élevé et je sais depuis le début qu’il me faudra beaucoup travailler dur pour m’en sortir. Qu’importe ! Je trouve l’ensemble des cours très intéressant et j’ai chaque fois hâte d’en apprendre davantage. Je réalise aussi que j’ai la chance d’avoir trouvé un secteur qui m’intéresse fortement et promet qui plus est des perspectives d’avenir confortables et au potentiel quasi illimité. 
La route est longue et il me faudra m’accrocher pour réussir. Ceci étant, je sais déjà que le jeu en vaut largement la chandelle.");
        $item1->setIntroduction("ou la rentrée d’un étudiant après une (longue) pause dans ses études.");
        $item1->setTitle("Rentrée 2.0");
        $item1->setCreationDate(new \DateTime("-0001-11-30 00:00:00"));
        $item1->setModificationDate(new \DateTime("-0001-11-30 00:00:00"));

        $manager->persist($item1);

        $item2 = new Article();
        $this->addReference('_reference_AppBundleEntityArticle2', $item2);
        $item2->setUser($this->getReference('_reference_AppBundleEntityUser1'));
        $item2->setContent("L’APCC (traduisez par Convention des Enfants d’Asie et du Pacifique) est un mouvement citoyen fondé par le Conseil des Jeunes de Fukuoka dans le cadre de l’Exposition Asie-Pacifique de 1989, évènement organisé pour célébrer le 100ème anniversaire de la ville de Fukuoka au Japon. 
Chaque année, des enfants âgés de 11 ans venant de toute l’Asie et de la région du Pacifique (incluant les délégations des villes jumelées avec la ville de Fukuoka dont Bordeaux fait partie) sont invités à participer à un programme qui dure deux semaines, bâti autour d’une thématique phare au Japon : la paix. A l’instar de beaucoup de pays de l’Europe de l’ouest, le Japon a connu lui aussi les traumatismes des guerres mondiales et notamment l’atrocité des bombardements atomiques. Raison pour laquelle la thématique de la paix est une valeur très forte, ancrée très profondément au pays du soleil levant. A l’heure actuelle, l’APCC est la plus importante convention organisée pour des enfants au monde.

En organisant cette convention, la ville de Fukuoka et tous les participants impliqués dans ce projet (bénévoles et salariés) espèrent participer à l’émergence de « citoyens du monde », capables de penser le monde au-delà des frontières entre nations, animés par l’esprit d’OMOIYARI (traduisez par paix et coexistence). Cette rencontre entre des enfants de pays totalement différents et éloignés géographiquement (tels que les pays d’Asie du Sud-Est, mais aussi les pays d’Océanie, la Russie, la ville de Bordeaux, la ville de Lima au Pérou, les villes d’Atlanta et d’Oakland aux Etats-Unis d’Amérique,…) est articulée autour de trois points : d’abord aider les enfants de ces pays et région à mieux se connaître, à découvrir leurs pays respectif par le biais de l’échange, ensuite promouvoir la compréhension mutuelle entre ces pays et régions, enfin encourager la jeunesse à développer une perspective internationale et promouvoir un environnement qui y soit favorable.

	Cette année, ce sont donc plus de 210 enfants venus du monde entier qui auront pu se rencontrer, échanger et tisser ensemble des liens d’amitiés internationales au travers d’un séjour dans un camp, de visite d’école, de spectacle de danses traditionnelles de leurs pays et en second lieu d’un séjour chez l’habitant, dans des familles bénévoles fortement impliquées dans ce projet à l’échelle de la ville de Fukuoka (1,5 millions d’habitants, plus grande ville de l’île de Kyushu). 

	Le slogan de l’APCC :  “We are the bridge : we connect dreams around the world” reflète bien l’idée principale de cette convention : à savoir la création d’un réseau international de personnes unis autour de valeurs fortes comme la paix et la compréhension mutuelle entre les différents peuples. A l’occasion de sa 10ème édition, chaque année, des anciens enfants qui ont participé à cette convention sont également invités pour continuer le maillage de ce tissu international aux promesses d’espoir et de paix.

	Cette soirée organisée à l’Hôtel de Ville de la Mairie de Bordeaux aura donc été, pour les quatre enfants qui ont participé à la 28ème édition, l’adulte accompagnateur, les parents des enfants et tous les acteurs de ce projet dont notamment le centre d’animation Argonne Nansouty Saint-Genès, l’occasion de se réunir pour échanger autour de cette formidable aventure humaine, et tenter à leur tour, de diffuser autant que faire se peut l’esprit d’Omoiyari, de partager et propager des valeurs de compréhension, de respect mutuel et de paix en ces temps si souvent troublés.");
        $item2->setIntroduction("Le jeudi 16 Novembre dernier s’est tenu la cérémonie de restitution de la 28ème édition de l’Asian Pacific Children Convention (APCC) à l’Hôtel de Ville de Bordeaux, pilotée par le service des Relations Internationales de la Mairie de Bordeaux et l’Association des Centres d’Animation de Quartiers de Bordeaux. ");
        $item2->setTitle("Worldwide Peace Network");
        $item2->setCreationDate(new \DateTime("-0001-11-30 00:00:00"));
        $item2->setModificationDate(new \DateTime("-0001-11-30 00:00:00"));

        $manager->persist($item2);

        $item3 = new Article();
        $this->addReference('_reference_AppBundleEntityArticle3', $item3);
        $item3->setUser($this->getReference('_reference_AppBundleEntityUser1'));
        $item3->setContent("    C’est au géant Webedia, premier groupe français dédié au loisir et au divertissement en ligne (qui détient jeuxvideos.com et millenium.fr) que nous devons ce projet web de grande envergure. Celui-ci est porté principalement par les deux géants français de Youtube Cyprien et Squeezie, qui totalisent à eux deux un peu moins de 20 millions d’abonnés sur leurs chaînes. Ces deux personnages bien connus du monde du web et qui ont un gros penchant gamer sont accompagnés d’autres streamers provenant de plateforme de streaming comme twitch : Maxildan, Gotaga, Laink et Terracid, Superzouloux, Kenny, Xari, Jiraya, Mickalow, Zankioh, Skyyart, Jimmy, Codjordan, Manamy,...

    Lestream.fr a pour ambition de devenir la chaîne française numéro un articulée autour d’émissions de gaming et de divertissement en ligne. Ce site propose donc un portail d’accueil qui retransmet l’émission en cours mais affiche également des onglets pour chaque streamer, annonçant à l’internaute si ces derniers sont en live sur leur chaîne personnelle.

    Pour la soirée de lancement nous aurons pu assister à la première d’une émission hebdomadaire baptisée Le Prime. D’un point de vue audience c’est véritablement carton plein ! Avec plus de 1 million de vues au total et 150.000 spectateurs simultanés, la petite équipe de streamers aura réussi son pari puisqu’il s’agit là de la meilleure audience pour une chaîne française sur twitch.tv, la plateforme de streaming de jeux vidéo. Pari réussi ? Assurément. Performance exemplaire ? Pas franchement. En effet l’internaute aura pu assister à une sorte de jeu télé mais en moins bien ! Des décors qui font très cheap et bricolés à la va-vite, des jeux et défis qui manquent de dynamisme voire d’originalité, le tout déroulé autour d’une présentation un peu brouillonne : on pourrait ainsi se demander si les deux années nécessaires à la création de lestream.fr auront été exploitées du mieux possible. 

    Le tableau n’est pas si noir toutefois puisqu’une grande partie des internautes s’avère très satisfaite du contenu qui a été proposé et se révèle d’ores et déjà très active sur le site lestream.fr qui propose également un système de classement des meilleurs internautes (temps passé à regarder les live, activité sur le site,…).
Même s’il y a encore des choses à dire et à redire sur cette performance, rappelons cependant qu’il s’agissait là de la première émission et qu’on ne peut qu’espérer que les prochaines s’amélioreront avec le temps.

    En tous les cas le pari est réussi pour Webedia, Cyprien, Squeezie et tous les autres, qui forts d’un franc succès d’audience et d’une énorme communauté pourront sans nul doute mener à bien leur projet et venir concurrencer des web tv bien implémentées comme Eclypsia.fr par exemple. Saluons en donc l’initiative et souhaitons-leur une bonne chance !");
        $item3->setIntroduction("Mercredi 8 mars dernier a eu lieu le lancement du site internet lestream.fr et de sa web tv.");
        $item3->setTitle("Lancement de LeStream.fr");
        $item3->setCreationDate(new \DateTime("-0001-11-30 00:00:00"));
        $item3->setModificationDate(new \DateTime("-0001-11-30 00:00:00"));

        $manager->persist($item3);

        $item4 = new Article();
        $this->addReference('_reference_AppBundleEntityArticle4', $item4);
        $item4->setUser($this->getReference('_reference_AppBundleEntityUser1'));
        $item4->setContent("Bonjour vous deux, est-ce que vous pourriez rapidement vous présenter, décrire votre 
parcours scolaire, votre choix de spécialisation,… ?

- Salut moi c’est Alexandre : j’ai 22 ans, je suis en 5ème année à Ingesup en ayant choisi l’option développement lors de ma 3ème année et je me suis dès lors spécialisé dans la BI. J’ai d’abord fait une alternance à Ynov en tant que développeur : je répondais aux questions des utilisateurs avec des tickets. Après j’ai eu une alternance chez Next Decision où j’ai fait intégralement du BI avec Talend et des bases de données.

- Moi je m’appelle Elisa : j’ai 21 ans et comme Alexandre j’ai intégré Ingesup dès la première année. Actuellement je suis en 4ème année en option développement. Depuis mon stage de fin d’année de B2 dans l’entreprise Aquitem ???? je me suis notamment spécialisée dans la gestion de bases de données.  A l’heure actuelle je suis toujours en alternance dans une entreprise et je fais de la base de données.

Pourriez-vous expliquer brièvement ce que sont le BI et le Big Data ?

- Elisa : le Big Data c’est la gestion massive de données : des quantités énormes de données qui s’auto alimentent et qui s’autogèrent.  Tout ça pour faire ensuite ressortir tout un tas de statistiques et autres calculs.

- Alexandre : la BI ça permet une aide à la décision : les entreprises ont besoin de données pour visualiser ce qu’elles font et surtout pouvoir anticiper ce qui va arriver. Ces données leur sont capitales. Le BI c’est donc l’analyse de leurs données.

Pourquoi avez-vous choisi de proposer ce labo ?

- A : Ca fait 2 ans que je fais de la BI en tant que consultant : j’ai  besoin d’apprendre à m’organiser, à vulgariser mon travail et expliquer ce qu’est la BI. Mais aussi parce que j’avais envie de partager mes domaines de compétences avec les étudiants des autres années et il faut dire que ça change de la relation enseignants/étudiants.

- E : Je trouve que l’on n’a pas la vision du Big Data assez tôt à Ingesup. Par conséquent les labos sont une super occasion d’apprendre autre chose que ce que l’on voit en cours. L’aspect teaching et transmission des données c’est comme ça que j’aime l’école !

C’est quoi le but de votre labo ? Vers quoi tendez-vous ?

A : Mon but c’est que les étudiants comprennent ce qu’est la BI et le Big Data, qu’ils y soient sensibilisés parce que c’est un secteur d’avenir et aussi qu’ils puissent monter en compétence.

E : Pour moi le but c’est de sensibiliser sur les enjeux du Big Data qui prend de plus en plus d’ampleurs. C’est un secteur auquel on ne pense pas forcément alors qu’il devient de plus en plus colossal !

Comment envisagez-vous l’évolution du Big Data et du BI dans l’avenir ?

E : C’est de plus en plus colossal : même si les entreprises n’y connaissent rien elles sentent déjà que c’est vraiment très important, aussi bien pour leurs clients que pour elles-mêmes. 

A : Quand on voit qu’il y a de plus en plus d’objets connectés (smartphones, tablettes, ordinateurs, etc.) il y a de plus en plus de données générées : le Big Data ça va vraiment être le secteur d’avenir.

Où vous voyez-vous dans 5 ans ?

A : A l’étranger. J’aimerais bien être consultant ou alors avoir un poste en interne de responsable chef de projet BI/Big Data.

E : A l’étranger aussi mais plutôt dba (ndlr : Administrateur de Base de Données) ou alors monter ma propre enreprise. 

Un petit mot pour la fin ?

E : On espère que le labo vous aura plus, que vous aurez envie d’en découvrir un peu plus et surtout que vous reviendez l’année prochaine ! 


A : J’espère que ce labo va continuer (ndlr : Alexandre finit ses études cette année) et qu’il va durer parce que c’est une matière qui a de l’avenir.


Un grand merci à eux et qu’ils se rassurent cela aura fonctionné (en tout cas chez moi) puisque je suis bien décidé à reprendre l’an procahain et à approfondir davantage le sujet ! ");
        $item4->setIntroduction("Pour ma première année d’études à Ingesup j’ai intégré le labo Business Intelligence (BI) & Big Data lors des Ydays, qui ont lieu les mercredis.
Puisque ce labo me plaît, que le sujet qu’il traite est chaque jour davantage d’actualité et qu’en plus mes directeurs de labo sont plutôt (très) sympas, je me suis dit que cela serait une bonne idée de les interviewer pour permettre à tous d’en savoir plus sur ce (chouette) labo !");
        $item4->setTitle("Interview Labo Bi");
        $item4->setCreationDate(new \DateTime("-0001-11-30 00:00:00"));
        $item4->setModificationDate(new \DateTime("-0001-11-30 00:00:00"));

        $manager->persist($item4);

        $item5 = new Article();
        $this->addReference('_reference_AppBundleEntityArticle5', $item5);
        $item5->setUser($this->getReference('_reference_AppBundleEntityUser1'));
        $item5->setContent("Bonjour Axel et merci de bien vouloir jouer le jeu de l’interview. Puisque tu es nouveau au sein de l’équipe pédagogique, est-ce que tu pourrais te présenter brièvement ?

Alors moi je m’appelle Axel Denjean et je suis en B3 à Ingésup. En B3 nous sommes en alternance et pour ma part j’effectue mon stage à l’administration d’Ynov. 

Quel est ton rôle au sein de l’administration ?

On peut dire que je suis le “second Jean-Marie” ! Je m’occupe des activités au sein de l’école et de leur communication. En gros je gère le BDE (Bureau Des Etudiants) puisque maintenant ce dernier n’est pas vraiment séparé de l’administration.

Puisque tu abordes le sujet du BDE, est-ce que tu pourrais nous en dire un peu plus ? En quoi ça consiste, c’est ouvert à qui ?

Cette année nous avons eu envie de nous écarter un peu du fonctionnement traditionnel. Désormais même sans faire partie du BDE chacun peut participer à une activité. Nous souhaitons également que tout le monde ait le droit de proposer une activité et puisse obtenir un budget alloué pour cette activité. 
Par exemple si tu veux organiser une soirée jeux vidéos et que tu souhaites avoir de la communication (affiches, post Facebook ou même un stand dans la caféteria), tu en as tout à fait le droit et en contrepartie moi je t’informe simplement de ce dont j’ai besoin pour que tu organises cet évènement. 

Y a-t-il une adresse spéciale où il faut effectuer ces demandes ?

Tout à fait. Il y a :
- la page Facebook du BDE
- mon adresse mèl : axel.denjean@ynov.com
- ou même si l’on me croise au sein de l’école on peut me demander directement

Est-ce que tu aurais un conseil à donner aux nouveaux étudiants (et pourquoi pas aux anciens) ?

Comme je l’ai déjà dit à beaucoup de gens, n’hésitez pas à profiter au maximum des activités qui sont proposées à l’école ! Puisque nous sommes deux personnes à nous occuper des activités cette année, il y en aura davantage. Toutes ces activités sont proposées au prix le plus bas possible et la plupart sont même gratuites. On aurait tort de s’en priver ! 
Ah oui et n’hésitez pas non plus à aller parler à l’administration si vous avez des questions, ils sont sympas !

Alors c’est noté ! Merci à Axel de nous avoir accordé de son temps pour répondre à mes questions. En espérant vous voir toujours plus nombreux aux activités du BDE !");
        $item5->setIntroduction("Une nouvelle année d’études commence pour moi et visiblement il n’y a pas que dans ma classe que de nouvelles têtes apparaissent... C’est le cas d’Axel, recrue toute “fraiche” de l’équipe pédagogique, qui a bien voulu répondre à mes questions.");
        $item5->setTitle("Interview Axel Denjean");
        $item5->setCreationDate(new \DateTime("-0001-11-30 00:00:00"));
        $item5->setModificationDate(new \DateTime("-0001-11-30 00:00:00"));

        $manager->persist($item5);

    
        $manager->flush();
    }

}
