<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\Comment;
use Doctrine\Bundle\FixturesBundle\Fixture;


/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadAppBundleEntityComment extends Fixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 3;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Comment::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item9 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment9', $item9);
        $item9->setAuteur($this->getReference('_reference_AppBundleEntityUser3'));
        $item9->setArticle($this->getReference('_reference_AppBundleEntityArticle1'));
        $item9->setContent("Bacon ipsum dolor amet bacon pork chop jerky turducken strip steak chicken tri-tip landjaeger meatball beef ribs. Pancetta sirloin ham, short loin alcatra tail picanha leberkas brisket tri-tip meatloaf sausage. Kielbasa cow salami turducken. Swine ham hock fatback meatloaf chuck. Spare ribs cow boudin hamburger andouille capicola turkey kielbasa pastrami alcatra pork belly sausage pork chop shankle.");
        $item9->setCreationDate(new \DateTime("2018-01-13 11:00:07"));
        $item9->setModificationDate(new \DateTime("2018-01-13 11:00:07"));
        $item9->setIsValid(true);

        $manager->persist($item9);

        $item10 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment10', $item10);
        $item10->setAuteur($this->getReference('_reference_AppBundleEntityUser3'));
        $item10->setArticle($this->getReference('_reference_AppBundleEntityArticle1'));
        $item10->setContent("Bacon ipsum dolor amet bacon pork chop jerky turducken strip steak chicken tri-tip landjaeger meatball beef ribs. Pancetta sirloin ham, short loin alcatra tail picanha leberkas brisket tri-tip meatloaf sausage. Kielbasa cow salami turducken. Swine ham hock fatback meatloaf chuck. Spare ribs cow boudin hamburger andouille capicola turkey kielbasa pastrami alcatra pork belly sausage pork chop shankle.");
        $item10->setCreationDate(new \DateTime("2018-01-13 11:00:34"));
        $item10->setModificationDate(new \DateTime("2018-01-13 11:00:34"));
        $item10->setIsValid(true);

        $manager->persist($item10);

        $item11 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment11', $item11);
        $item11->setAuteur($this->getReference('_reference_AppBundleEntityUser2'));
        $item11->setArticle($this->getReference('_reference_AppBundleEntityArticle1'));
        $item11->setContent("Bonbon pudding tiramisu cookie icing candy halvah macaroon wafer. Sugar plum sugar plum gummies marzipan biscuit powder. Carrot cake carrot cake tootsie roll. Wafer apple pie dragée wafer bear claw. Bonbon chocolate cake gummies gingerbread brownie cupcake. Pudding chocolate pudding cheesecake lemon drops. Apple pie sugar plum caramels bonbon chocolate cake tiramisu jelly-o wafer jelly beans. Tootsie roll muffin dragée brownie cotton candy chupa chups soufflé. Chocolate bar sesame snaps cupcake sweet marshmallow cupcake tootsie roll carrot cake wafer. Marzipan cotton candy icing jelly. Pastry chupa chups sesame snaps oat cake. Cookie candy canes candy liquorice.");
        $item11->setCreationDate(new \DateTime("2018-01-13 11:00:55"));
        $item11->setModificationDate(new \DateTime("2018-01-13 11:00:55"));
        $item11->setIsValid(true);

        $manager->persist($item11);

        $item12 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment12', $item12);
        $item12->setAuteur($this->getReference('_reference_AppBundleEntityUser2'));
        $item12->setArticle($this->getReference('_reference_AppBundleEntityArticle1'));
        $item12->setContent("Bonbon pudding tiramisu cookie icing candy halvah macaroon wafer. Sugar plum sugar plum gummies marzipan biscuit powder. Carrot cake carrot cake tootsie roll. Wafer apple pie dragée wafer bear claw. Bonbon chocolate cake gummies gingerbread brownie cupcake. Pudding chocolate pudding cheesecake lemon drops. Apple pie sugar plum caramels bonbon chocolate cake tiramisu jelly-o wafer jelly beans. Tootsie roll muffin dragée brownie cotton candy chupa chups soufflé. Chocolate bar sesame snaps cupcake sweet marshmallow cupcake tootsie roll carrot cake wafer. Marzipan cotton candy icing jelly. Pastry chupa chups sesame snaps oat cake. Cookie candy canes candy liquorice.");
        $item12->setCreationDate(new \DateTime("2018-01-13 11:01:05"));
        $item12->setModificationDate(new \DateTime("2018-01-13 11:01:05"));
        $item12->setIsValid(true);

        $manager->persist($item12);

        $item13 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment13', $item13);
        $item13->setAuteur($this->getReference('_reference_AppBundleEntityUser3'));
        $item13->setArticle($this->getReference('_reference_AppBundleEntityArticle2'));
        $item13->setContent("Bacon ipsum dolor amet bacon pork chop jerky turducken strip steak chicken tri-tip landjaeger meatball beef ribs. Pancetta sirloin ham, short loin alcatra tail picanha leberkas brisket tri-tip meatloaf sausage. Kielbasa cow salami turducken. Swine ham hock fatback meatloaf chuck. Spare ribs cow boudin hamburger andouille capicola turkey kielbasa pastrami alcatra pork belly sausage pork chop shankle.");
        $item13->setCreationDate(new \DateTime("2018-01-13 11:00:07"));
        $item13->setModificationDate(new \DateTime("2018-01-13 11:00:07"));
        $item13->setIsValid(true);

        $manager->persist($item13);

        $item14 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment14', $item14);
        $item14->setAuteur($this->getReference('_reference_AppBundleEntityUser3'));
        $item14->setArticle($this->getReference('_reference_AppBundleEntityArticle2'));
        $item14->setContent("Bacon ipsum dolor amet bacon pork chop jerky turducken strip steak chicken tri-tip landjaeger meatball beef ribs. Pancetta sirloin ham, short loin alcatra tail picanha leberkas brisket tri-tip meatloaf sausage. Kielbasa cow salami turducken. Swine ham hock fatback meatloaf chuck. Spare ribs cow boudin hamburger andouille capicola turkey kielbasa pastrami alcatra pork belly sausage pork chop shankle.");
        $item14->setCreationDate(new \DateTime("2018-01-13 11:00:34"));
        $item14->setModificationDate(new \DateTime("2018-01-13 11:00:34"));
        $item14->setIsValid(true);

        $manager->persist($item14);

        $item15 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment15', $item15);
        $item15->setAuteur($this->getReference('_reference_AppBundleEntityUser2'));
        $item15->setArticle($this->getReference('_reference_AppBundleEntityArticle2'));
        $item15->setContent("Bonbon pudding tiramisu cookie icing candy halvah macaroon wafer. Sugar plum sugar plum gummies marzipan biscuit powder. Carrot cake carrot cake tootsie roll. Wafer apple pie dragée wafer bear claw. Bonbon chocolate cake gummies gingerbread brownie cupcake. Pudding chocolate pudding cheesecake lemon drops. Apple pie sugar plum caramels bonbon chocolate cake tiramisu jelly-o wafer jelly beans. Tootsie roll muffin dragée brownie cotton candy chupa chups soufflé. Chocolate bar sesame snaps cupcake sweet marshmallow cupcake tootsie roll carrot cake wafer. Marzipan cotton candy icing jelly. Pastry chupa chups sesame snaps oat cake. Cookie candy canes candy liquorice.");
        $item15->setCreationDate(new \DateTime("2018-01-13 11:00:55"));
        $item15->setModificationDate(new \DateTime("2018-01-13 11:00:55"));
        $item15->setIsValid(true);

        $manager->persist($item15);

        $item16 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment16', $item16);
        $item16->setAuteur($this->getReference('_reference_AppBundleEntityUser2'));
        $item16->setArticle($this->getReference('_reference_AppBundleEntityArticle2'));
        $item16->setContent("Bonbon pudding tiramisu cookie icing candy halvah macaroon wafer. Sugar plum sugar plum gummies marzipan biscuit powder. Carrot cake carrot cake tootsie roll. Wafer apple pie dragée wafer bear claw. Bonbon chocolate cake gummies gingerbread brownie cupcake. Pudding chocolate pudding cheesecake lemon drops. Apple pie sugar plum caramels bonbon chocolate cake tiramisu jelly-o wafer jelly beans. Tootsie roll muffin dragée brownie cotton candy chupa chups soufflé. Chocolate bar sesame snaps cupcake sweet marshmallow cupcake tootsie roll carrot cake wafer. Marzipan cotton candy icing jelly. Pastry chupa chups sesame snaps oat cake. Cookie candy canes candy liquorice.");
        $item16->setCreationDate(new \DateTime("2018-01-13 11:01:05"));
        $item16->setModificationDate(new \DateTime("2018-01-13 11:01:05"));
        $item16->setIsValid(true);

        $manager->persist($item16);

        $item17 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment17', $item17);
        $item17->setAuteur($this->getReference('_reference_AppBundleEntityUser3'));
        $item17->setArticle($this->getReference('_reference_AppBundleEntityArticle3'));
        $item17->setContent("Bacon ipsum dolor amet bacon pork chop jerky turducken strip steak chicken tri-tip landjaeger meatball beef ribs. Pancetta sirloin ham, short loin alcatra tail picanha leberkas brisket tri-tip meatloaf sausage. Kielbasa cow salami turducken. Swine ham hock fatback meatloaf chuck. Spare ribs cow boudin hamburger andouille capicola turkey kielbasa pastrami alcatra pork belly sausage pork chop shankle.");
        $item17->setCreationDate(new \DateTime("2018-01-13 11:00:07"));
        $item17->setModificationDate(new \DateTime("2018-01-13 11:00:07"));
        $item17->setIsValid(true);

        $manager->persist($item17);

        $item18 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment18', $item18);
        $item18->setAuteur($this->getReference('_reference_AppBundleEntityUser3'));
        $item18->setArticle($this->getReference('_reference_AppBundleEntityArticle3'));
        $item18->setContent("Bacon ipsum dolor amet bacon pork chop jerky turducken strip steak chicken tri-tip landjaeger meatball beef ribs. Pancetta sirloin ham, short loin alcatra tail picanha leberkas brisket tri-tip meatloaf sausage. Kielbasa cow salami turducken. Swine ham hock fatback meatloaf chuck. Spare ribs cow boudin hamburger andouille capicola turkey kielbasa pastrami alcatra pork belly sausage pork chop shankle.");
        $item18->setCreationDate(new \DateTime("2018-01-13 11:00:34"));
        $item18->setModificationDate(new \DateTime("2018-01-13 11:00:34"));
        $item18->setIsValid(true);

        $manager->persist($item18);

        $item19 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment19', $item19);
        $item19->setAuteur($this->getReference('_reference_AppBundleEntityUser2'));
        $item19->setArticle($this->getReference('_reference_AppBundleEntityArticle3'));
        $item19->setContent("Bonbon pudding tiramisu cookie icing candy halvah macaroon wafer. Sugar plum sugar plum gummies marzipan biscuit powder. Carrot cake carrot cake tootsie roll. Wafer apple pie dragée wafer bear claw. Bonbon chocolate cake gummies gingerbread brownie cupcake. Pudding chocolate pudding cheesecake lemon drops. Apple pie sugar plum caramels bonbon chocolate cake tiramisu jelly-o wafer jelly beans. Tootsie roll muffin dragée brownie cotton candy chupa chups soufflé. Chocolate bar sesame snaps cupcake sweet marshmallow cupcake tootsie roll carrot cake wafer. Marzipan cotton candy icing jelly. Pastry chupa chups sesame snaps oat cake. Cookie candy canes candy liquorice.");
        $item19->setCreationDate(new \DateTime("2018-01-13 11:00:55"));
        $item19->setModificationDate(new \DateTime("2018-01-13 11:00:55"));
        $item19->setIsValid(true);

        $manager->persist($item19);

        $item20 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment20', $item20);
        $item20->setAuteur($this->getReference('_reference_AppBundleEntityUser2'));
        $item20->setArticle($this->getReference('_reference_AppBundleEntityArticle3'));
        $item20->setContent("Bonbon pudding tiramisu cookie icing candy halvah macaroon wafer. Sugar plum sugar plum gummies marzipan biscuit powder. Carrot cake carrot cake tootsie roll. Wafer apple pie dragée wafer bear claw. Bonbon chocolate cake gummies gingerbread brownie cupcake. Pudding chocolate pudding cheesecake lemon drops. Apple pie sugar plum caramels bonbon chocolate cake tiramisu jelly-o wafer jelly beans. Tootsie roll muffin dragée brownie cotton candy chupa chups soufflé. Chocolate bar sesame snaps cupcake sweet marshmallow cupcake tootsie roll carrot cake wafer. Marzipan cotton candy icing jelly. Pastry chupa chups sesame snaps oat cake. Cookie candy canes candy liquorice.");
        $item20->setCreationDate(new \DateTime("2018-01-13 11:01:05"));
        $item20->setModificationDate(new \DateTime("2018-01-13 11:01:05"));
        $item20->setIsValid(true);

        $manager->persist($item20);

        $item21 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment21', $item21);
        $item21->setAuteur($this->getReference('_reference_AppBundleEntityUser3'));
        $item21->setArticle($this->getReference('_reference_AppBundleEntityArticle4'));
        $item21->setContent("Bacon ipsum dolor amet bacon pork chop jerky turducken strip steak chicken tri-tip landjaeger meatball beef ribs. Pancetta sirloin ham, short loin alcatra tail picanha leberkas brisket tri-tip meatloaf sausage. Kielbasa cow salami turducken. Swine ham hock fatback meatloaf chuck. Spare ribs cow boudin hamburger andouille capicola turkey kielbasa pastrami alcatra pork belly sausage pork chop shankle.");
        $item21->setCreationDate(new \DateTime("2018-01-13 11:00:07"));
        $item21->setModificationDate(new \DateTime("2018-01-13 11:00:07"));
        $item21->setIsValid(true);

        $manager->persist($item21);

        $item22 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment22', $item22);
        $item22->setAuteur($this->getReference('_reference_AppBundleEntityUser3'));
        $item22->setArticle($this->getReference('_reference_AppBundleEntityArticle4'));
        $item22->setContent("Bacon ipsum dolor amet bacon pork chop jerky turducken strip steak chicken tri-tip landjaeger meatball beef ribs. Pancetta sirloin ham, short loin alcatra tail picanha leberkas brisket tri-tip meatloaf sausage. Kielbasa cow salami turducken. Swine ham hock fatback meatloaf chuck. Spare ribs cow boudin hamburger andouille capicola turkey kielbasa pastrami alcatra pork belly sausage pork chop shankle.");
        $item22->setCreationDate(new \DateTime("2018-01-13 11:00:34"));
        $item22->setModificationDate(new \DateTime("2018-01-13 11:00:34"));
        $item22->setIsValid(true);

        $manager->persist($item22);

        $item23 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment23', $item23);
        $item23->setAuteur($this->getReference('_reference_AppBundleEntityUser2'));
        $item23->setArticle($this->getReference('_reference_AppBundleEntityArticle4'));
        $item23->setContent("Bonbon pudding tiramisu cookie icing candy halvah macaroon wafer. Sugar plum sugar plum gummies marzipan biscuit powder. Carrot cake carrot cake tootsie roll. Wafer apple pie dragée wafer bear claw. Bonbon chocolate cake gummies gingerbread brownie cupcake. Pudding chocolate pudding cheesecake lemon drops. Apple pie sugar plum caramels bonbon chocolate cake tiramisu jelly-o wafer jelly beans. Tootsie roll muffin dragée brownie cotton candy chupa chups soufflé. Chocolate bar sesame snaps cupcake sweet marshmallow cupcake tootsie roll carrot cake wafer. Marzipan cotton candy icing jelly. Pastry chupa chups sesame snaps oat cake. Cookie candy canes candy liquorice.");
        $item23->setCreationDate(new \DateTime("2018-01-13 11:00:55"));
        $item23->setModificationDate(new \DateTime("2018-01-13 11:00:55"));
        $item23->setIsValid(true);

        $manager->persist($item23);

        $item24 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment24', $item24);
        $item24->setAuteur($this->getReference('_reference_AppBundleEntityUser2'));
        $item24->setArticle($this->getReference('_reference_AppBundleEntityArticle4'));
        $item24->setContent("Bonbon pudding tiramisu cookie icing candy halvah macaroon wafer. Sugar plum sugar plum gummies marzipan biscuit powder. Carrot cake carrot cake tootsie roll. Wafer apple pie dragée wafer bear claw. Bonbon chocolate cake gummies gingerbread brownie cupcake. Pudding chocolate pudding cheesecake lemon drops. Apple pie sugar plum caramels bonbon chocolate cake tiramisu jelly-o wafer jelly beans. Tootsie roll muffin dragée brownie cotton candy chupa chups soufflé. Chocolate bar sesame snaps cupcake sweet marshmallow cupcake tootsie roll carrot cake wafer. Marzipan cotton candy icing jelly. Pastry chupa chups sesame snaps oat cake. Cookie candy canes candy liquorice.");
        $item24->setCreationDate(new \DateTime("2018-01-13 11:01:05"));
        $item24->setModificationDate(new \DateTime("2018-01-13 11:01:05"));
        $item24->setIsValid(true);

        $manager->persist($item24);

        $item25 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment25', $item25);
        $item25->setAuteur($this->getReference('_reference_AppBundleEntityUser3'));
        $item25->setArticle($this->getReference('_reference_AppBundleEntityArticle5'));
        $item25->setContent("Bacon ipsum dolor amet bacon pork chop jerky turducken strip steak chicken tri-tip landjaeger meatball beef ribs. Pancetta sirloin ham, short loin alcatra tail picanha leberkas brisket tri-tip meatloaf sausage. Kielbasa cow salami turducken. Swine ham hock fatback meatloaf chuck. Spare ribs cow boudin hamburger andouille capicola turkey kielbasa pastrami alcatra pork belly sausage pork chop shankle.");
        $item25->setCreationDate(new \DateTime("2018-01-13 11:00:07"));
        $item25->setModificationDate(new \DateTime("2018-01-13 11:00:07"));
        $item25->setIsValid(true);

        $manager->persist($item25);

        $item26 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment26', $item26);
        $item26->setAuteur($this->getReference('_reference_AppBundleEntityUser3'));
        $item26->setArticle($this->getReference('_reference_AppBundleEntityArticle5'));
        $item26->setContent("Bacon ipsum dolor amet bacon pork chop jerky turducken strip steak chicken tri-tip landjaeger meatball beef ribs. Pancetta sirloin ham, short loin alcatra tail picanha leberkas brisket tri-tip meatloaf sausage. Kielbasa cow salami turducken. Swine ham hock fatback meatloaf chuck. Spare ribs cow boudin hamburger andouille capicola turkey kielbasa pastrami alcatra pork belly sausage pork chop shankle.");
        $item26->setCreationDate(new \DateTime("2018-01-13 11:00:34"));
        $item26->setModificationDate(new \DateTime("2018-01-13 11:00:34"));
        $item26->setIsValid(true);

        $manager->persist($item26);

        $item27 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment27', $item27);
        $item27->setAuteur($this->getReference('_reference_AppBundleEntityUser2'));
        $item27->setArticle($this->getReference('_reference_AppBundleEntityArticle5'));
        $item27->setContent("Bonbon pudding tiramisu cookie icing candy halvah macaroon wafer. Sugar plum sugar plum gummies marzipan biscuit powder. Carrot cake carrot cake tootsie roll. Wafer apple pie dragée wafer bear claw. Bonbon chocolate cake gummies gingerbread brownie cupcake. Pudding chocolate pudding cheesecake lemon drops. Apple pie sugar plum caramels bonbon chocolate cake tiramisu jelly-o wafer jelly beans. Tootsie roll muffin dragée brownie cotton candy chupa chups soufflé. Chocolate bar sesame snaps cupcake sweet marshmallow cupcake tootsie roll carrot cake wafer. Marzipan cotton candy icing jelly. Pastry chupa chups sesame snaps oat cake. Cookie candy canes candy liquorice.");
        $item27->setCreationDate(new \DateTime("2018-01-13 11:00:55"));
        $item27->setModificationDate(new \DateTime("2018-01-13 11:00:55"));
        $item27->setIsValid(true);

        $manager->persist($item27);

        $item28 = new Comment();
        $this->addReference('_reference_AppBundleEntityComment28', $item28);
        $item28->setAuteur($this->getReference('_reference_AppBundleEntityUser2'));
        $item28->setArticle($this->getReference('_reference_AppBundleEntityArticle5'));
        $item28->setContent("Bonbon pudding tiramisu cookie icing candy halvah macaroon wafer. Sugar plum sugar plum gummies marzipan biscuit powder. Carrot cake carrot cake tootsie roll. Wafer apple pie dragée wafer bear claw. Bonbon chocolate cake gummies gingerbread brownie cupcake. Pudding chocolate pudding cheesecake lemon drops. Apple pie sugar plum caramels bonbon chocolate cake tiramisu jelly-o wafer jelly beans. Tootsie roll muffin dragée brownie cotton candy chupa chups soufflé. Chocolate bar sesame snaps cupcake sweet marshmallow cupcake tootsie roll carrot cake wafer. Marzipan cotton candy icing jelly. Pastry chupa chups sesame snaps oat cake. Cookie candy canes candy liquorice.");
        $item28->setCreationDate(new \DateTime("2018-01-13 11:01:05"));
        $item28->setModificationDate(new \DateTime("2018-01-13 11:01:05"));
        $item28->setIsValid(true);

        $manager->persist($item28);

    
        $manager->flush();
    }

}
