<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\Competence;
use Doctrine\Bundle\FixturesBundle\Fixture;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadAppBundleEntityCompetence extends Fixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Competence::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item10 = new Competence();
        $this->addReference('_reference_AppBundleEntityCompetence10', $item10);
        $item10->setTitle("Cisco");
        $item10->setImageName("cisco.png");
        $item10->setUpdatedAt(new \DateTime("2018-01-14 13:26:39"));

        $manager->persist($item10);

        $item11 = new Competence();
        $this->addReference('_reference_AppBundleEntityCompetence11', $item11);
        $item11->setTitle("Bash");
        $item11->setImageName("bash.png");
        $item11->setUpdatedAt(new \DateTime("2018-01-14 13:27:04"));

        $manager->persist($item11);

        $item12 = new Competence();
        $this->addReference('_reference_AppBundleEntityCompetence12', $item12);
        $item12->setTitle("java");
        $item12->setImageName("java.png");
        $item12->setUpdatedAt(new \DateTime("2018-01-14 13:27:16"));

        $manager->persist($item12);

        $item13 = new Competence();
        $this->addReference('_reference_AppBundleEntityCompetence13', $item13);
        $item13->setTitle("linux");
        $item13->setImageName("linux.png");
        $item13->setUpdatedAt(new \DateTime("2018-01-14 13:27:23"));

        $manager->persist($item13);

        $item14 = new Competence();
        $this->addReference('_reference_AppBundleEntityCompetence14', $item14);
        $item14->setTitle("oracle");
        $item14->setImageName("oracle.png");
        $item14->setUpdatedAt(new \DateTime("2018-01-14 13:27:33"));

        $manager->persist($item14);

        $item15 = new Competence();
        $this->addReference('_reference_AppBundleEntityCompetence15', $item15);
        $item15->setTitle("Plsql");
        $item15->setImageName("plsql.png");
        $item15->setUpdatedAt(new \DateTime("2018-01-14 13:27:40"));

        $manager->persist($item15);

        $item16 = new Competence();
        $this->addReference('_reference_AppBundleEntityCompetence16', $item16);
        $item16->setTitle("python");
        $item16->setImageName("python.png");
        $item16->setUpdatedAt(new \DateTime("2018-01-14 13:27:58"));

        $manager->persist($item16);

        $item17 = new Competence();
        $this->addReference('_reference_AppBundleEntityCompetence17', $item17);
        $item17->setTitle("talend");
        $item17->setImageName("talend.png");
        $item17->setUpdatedAt(new \DateTime("2018-01-14 13:28:05"));

        $manager->persist($item17);

        $item18 = new Competence();
        $this->addReference('_reference_AppBundleEntityCompetence18', $item18);
        $item18->setTitle("winserver");
        $item18->setImageName("winserver.png");
        $item18->setUpdatedAt(new \DateTime("2018-01-14 13:28:11"));

        $manager->persist($item18);

    
        $manager->flush();
    }

}
