<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\Intro;
use Doctrine\Bundle\FixturesBundle\Fixture;


/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadAppBundleEntityIntro extends Fixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Intro::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new Intro();
        $this->addReference('_reference_AppBundleEntityIntro1', $item1);
        $item1->setPhraseIntro("Etudiant 2ème année Ingésup Ynov Bordeaux");
        $item1->setAboutMe("Stage orienté Systèmes et Réseaux juin-juillet-août 2018
Alternance pour l'année scolaire 2018-2019");

        $manager->persist($item1);

    
        $manager->flush();
    }

}
